substitutions:
  _REGION: "us-west1"
  _REPO: "web"              # 你创建的 Artifact Registry Docker 仓库名
  _SERVICE: "recat-web"     # Cloud Run 服务名
  _IMAGE: "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA}"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_IMAGE}", "."]

  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_IMAGE}"]

  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_IMAGE}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
      - --max-instances=2
      - --memory=256Mi
      - --cpu=1

images:
  - ${_IMAGE}

timeout: "1200s"